### ISSUE TITLE
exception at 'stop' goal

### ISSUE THREAD

**Issue by dantran** [Zetten/xvfb-maven-plugin#4]
Not sure why I run into this issue (java 7, maven 3.3.9, linux)

Exception in thread "Thread-3" java.lang.NoClassDefFoundError: com/github/zetten/maven/xvfb/AbstractXvfbMojo$1
    at com.github.zetten.maven.xvfb.AbstractXvfbMojo.destroyXvfb(AbstractXvfbMojo.java:168)
    at com.github.zetten.maven.xvfb.XvfbRunMojo$1.run(XvfbRunMojo.java:77)
Caused by: java.lang.ClassNotFoundException: com.github.zetten.maven.xvfb.AbstractXvfbMojo$1
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    ... 2 more

**Comment by Zetten** [comment]
I'm not able to reproduce this myself, testing with OpenJDK 1.7.0_101 (and 1.8.0_92) and Maven 3.3.9 on Linux.

The error is that the anonymous inner Callable class isn't available - what's the rest of your environment like? Are you running in an IDE or on the command line? Are there any other Maven plugins which might affect the classloader?

Perhaps to narrow down environmental issues, are you able to build the plugin from source and run the ITs with `mvn verify -Prun-its`? (The GPG error may be ignored, or suppressed with `-Dgpg.skip`)

**Comment by Toilal** [comment]
I just hit this issue while migrating my jenkins server to a new machine. I'm investigating ...

CentOS Linux release 7.2.1511 - Java 8u102 - Maven 3.3.9

**Comment by Toilal** [comment]
I just build and run the integration tests on the Jenkins server where problem occurs, but it works fine. I'm using the same maven installation and settings as for my main project (which is failling because of this issue). ([Logs](https://gist.github.com/Toilal/07f1b810d750707dbb732e3b4dc37a12))

**Comment by Toilal** [comment]
I've switched to Jenkins Xvfb plugin as a workaround.

**Comment by Zetten** [comment]
This is really baffling. There must be something going on with the Maven plugin classloader, but I can't imagine what (not that I know much about it), and I still haven't seen the problem pop up on any of my own builds  😞 

Can you "mvn install" your locally-built version of the plugin, and see if your project build works with that? I would hope that if the ITs pass in your environment it should be fine in real use...

**Comment by Toilal** [comment]
I tried to manually mvn install from development branch, and the used the produced 1.2.0-SNAPSHOT version, but problem is still there.

I also think there's something wrong with the Maven plugin classloader (plexus thing), but I can't find any information about this. Note i'm running OpenJDK, not the Oracle version.

Sadly i'm leaving this environment because it's the end of my mission, so I won't be able to make further tests.
